### ISSUE TITLE
BRepBuilderAPI_MakeSolid has no accessible constructor

### ISSUE THREAD

**Issue by Sea-DH1** [donalffons/opencascade.js#93]
In this way, an error will be reported directly
![image](https://user-images.githubusercontent.com/26751491/145739060-c9bd958d-18f3-4ad6-903d-3c83b6200303.png)

![image](https://user-images.githubusercontent.com/26751491/145739013-190c0884-39bb-4fe6-980f-fc4b197a925a.png)

**Comment by donalffons** [comment]
Hi, this is expected behavior and is mentioned in [the docs](https://github.com/donalffons/opencascade.js/blob/master/doc/README.md#overloaded-methods). You might want to try using `BRepBuilderAPI_MakeSolid_1` instead, which will give you the first overload of that constructor.
Let me know if that works for you. Cheers.
